{{- if and .Values.externalSecret.enabled .Values.secretStore.create (eq .Values.externalSecret.secretStoreRef.kind "SecretStore") }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "bcp-ingestion-pipeline.secretStoreName" . }}
  labels:
    {{- include "bcp-ingestion-pipeline.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: {{ .Values.secretStore.aws.service | quote }}
      region: {{ .Values.secretStore.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "bcp-ingestion-pipeline.serviceAccountName" . }}
      {{- with .Values.secretStore.aws.role }}
      role: {{ . | quote }}
      {{- end }}
{{- end }}
