# -*- coding: utf-8 -*-
"""Fundamentals_AI_Summary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173RNNAXzxZctYvTow-NciwFsC-8DXFkb
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import AWS_RDS, TICKER_MAPPINGS, OPENAI_API_KEY, FMP_API_KEY

# !pip install requests feedparser numpy pandas yfinance
import feedparser
from config import AWS_RDS, TICKER_MAPPINGS, OPENAI_API_KEY,FMP_API_KEY

import requests
import feedparser
import numpy as np
import yfinance as yf
import pandas as pd
from datetime import datetime, timezone
from urllib.parse import quote_plus



# Derive country from ticker suffix
_SUFFIX_TO_COUNTRY = {
    "HK": "HK", "KS": "KR", "T": "JP", "ST": "CH",
    "DE": "DE", "AX": "AU", "US": "US",
}
# Stocks that require yfinance fallback instead of FMP
_YFINANCE_TICKERS = {"6887.HK"}

def _get_country(ticker):
    parts = ticker.rsplit(".", 1)
    if len(parts) == 2:
        return _SUFFIX_TO_COUNTRY.get(parts[1].upper(), "US")
    return "US"

def _fetch_stocks_ai():
    try:
        import psycopg2 as _pg
        conn = _pg.connect(
            host=AWS_RDS["host"], port=AWS_RDS["port"],
            database=AWS_RDS["database"], user=AWS_RDS["user"],
            password=AWS_RDS["password"], sslmode=AWS_RDS["sslmode"]
        )
        cur = conn.cursor()
        cur.execute("""
            SELECT ticker, company_name FROM ingest_db.stocks
            WHERE is_peer = false ORDER BY stock_id
        """)
        result = [
            {
                "symbol": row[0],
                "name": row[1],
                "country": _get_country(row[0]),
                "source": "yfinance" if row[0] in _YFINANCE_TICKERS else "fmp"
            }
            for row in cur.fetchall()
        ]
        cur.close()
        conn.close()
        print(f"[fetch_ai_summary_fundamentals] Loaded {len(result)} stocks from DB")
        return result
    except Exception as e:
        print(f"[fetch_ai_summary_fundamentals] Warning: Could not fetch stocks from DB: {e}")
        return []

STOCKS = _fetch_stocks_ai()

BENCHMARKS = {
    "HK": {"symbol": "^HSI",   "name": "Hang Seng Index"},
    "KR": {"symbol": "^KS11",  "name": "KOSPI"},
    "JP": {"symbol": "^N225",  "name": "Nikkei 225"},
    "CH": {"symbol": "^SSMI",  "name": "Swiss Market Index"},
    "DE": {"symbol": "^GDAXI", "name": "DAX"},
    "AU": {"symbol": "^AXJO",  "name": "S&P/ASX 200"},
    "US": {"symbol": "^IXIC",  "name": "NASDAQ Composite"},
}

benchmark_cache = {}


def fmp(url):
    r = requests.get(url, timeout=20)
    r.raise_for_status()
    return r.json()

def fetch_news(symbol, name, limit=5):
    query = quote_plus(f"({name} OR {symbol})")
    url = f"https://news.google.com/rss/search?q={query}&hl=en-US&gl=US&ceid=US:en"
    feed = feedparser.parse(url)

    return [{
        "title": e.title,
        "published": e.published,
        "source": e.source.title if "source" in e else "Google News",
        "url": e.link
    } for e in feed.entries[:limit]]

def volume_zscore(volumes):
    if len(volumes) < 2:
        return 0, "Low", 0, 0

    today = volumes[0]
    hist = volumes[1:min(31, len(volumes))]

    mean = np.mean(hist)
    std = np.std(hist)
    z = 0 if std == 0 else (today - mean) / std

    if z >= 2:
        flag = "High"
    elif z >= 1:
        flag = "Medium"
    else:
        flag = "Low"

    return float(round(z, 2)), flag, int(today), int(mean)

def get_benchmark_30d(country):
    bm = BENCHMARKS[country]
    sym = bm["symbol"]

    if sym not in benchmark_cache:
        hist = fmp(
            f"https://financialmodelingprep.com/stable/historical-price-eod/full"
            f"?symbol={sym}&apikey={FMP_API_KEY}"
        )
        benchmark_cache[sym] = round(
            (hist[0]["close"] / hist[30]["close"] - 1) * 100, 2
        )

    return bm["name"], benchmark_cache[sym]

def fetch_yfinance_data(symbol, name, country):
    """Fetch stock data using yfinance and format it like FMP output"""
    try:
        ticker = yf.Ticker(symbol)

        # Get historical data (3 months to ensure we have enough)
        hist = ticker.history(period="3mo")

        if hist.empty:
            print(f"⚠️ No historical data for {symbol}")
            return None

        # Get current info
        info = ticker.info

        # Calculate metrics
        current_price = float(hist['Close'].iloc[-1])
        prev_close = float(hist['Close'].iloc[-2]) if len(hist) > 1 else current_price
        change_pct = ((current_price - prev_close) / prev_close) * 100

        # Get volumes
        volumes = hist['Volume'].tolist()
        volumes.reverse()  # Most recent first

        # Get closes for 30d and 60d calculations
        closes = hist['Close'].tolist()
        closes.reverse()  # Most recent first

        # Calculate moving averages
        ma_50 = float(hist['Close'].rolling(window=50).mean().iloc[-1]) if len(hist) >= 50 else current_price
        ma_200 = float(hist['Close'].rolling(window=200).mean().iloc[-1]) if len(hist) >= 200 else current_price

        # Get 52-week high
        year_high = info.get('fiftyTwoWeekHigh', float(hist['High'].max()))

        # Volume analysis
        z, vol_flag, today_vol, avg_vol = volume_zscore(volumes)

        # Benchmark comparison
        benchmark_name, benchmark_30d = get_benchmark_30d(country)
        stock_30d = (closes[0] / closes[min(30, len(closes)-1)] - 1) * 100 if len(closes) > 30 else 0

        return {
            "symbol": symbol,
            "name": name,
            "price": round(current_price, 2),
            "change_pct_1d": round(change_pct, 2),
            "market_cap": int(info.get('marketCap', 0)),

            "trend": {
                "above_50dma": bool(current_price > ma_50),
                "above_200dma": bool(current_price > ma_200),
                "distance_from_52w_high_pct": round(
                    (current_price / year_high - 1) * 100, 2
                )
            },

            "volume": {
                "today": today_vol,
                "avg_30d": avg_vol,
                "zscore": z,
                "flag": vol_flag
            },

            "relative_strength": {
                "stock_30d": round(stock_30d, 2),
                "benchmark": benchmark_name,
                "benchmark_30d": benchmark_30d,
                "relative": round(stock_30d - benchmark_30d, 2)
            },

            "news": fetch_news(symbol, name)
        }

    except Exception as e:
        print(f"Error fetching yfinance data for {symbol}: {e}")
        return None


def fetch_fmp_data(symbol, name, country):
    """Fetch stock data using FMP"""
    try:
        quote_data = fmp(
            f"https://financialmodelingprep.com/stable/quote"
            f"?symbol={symbol}&apikey={FMP_API_KEY}"
        )

        if not quote_data:
            print(f" No quote data for {symbol} from FMP")
            return None

        quote = quote_data[0]

        price_hist = fmp(
            f"https://financialmodelingprep.com/stable/historical-price-eod/full"
            f"?symbol={symbol}&apikey={FMP_API_KEY}"
        )

        closes = [d["close"] for d in price_hist[:60]]
        volumes = [d["volume"] for d in price_hist[:31]]

        z, vol_flag, today_vol, avg_vol = volume_zscore(volumes)

        benchmark_name, benchmark_30d = get_benchmark_30d(country)
        stock_30d = (closes[0] / closes[30] - 1) * 100

        return {
            "symbol": symbol,
            "name": name,
            "price": quote["price"],
            "change_pct_1d": quote["changePercentage"],
            "market_cap": quote["marketCap"],

            "trend": {
                "above_50dma": bool(quote["price"] > quote["priceAvg50"]),
                "above_200dma": bool(quote["price"] > quote["priceAvg200"]),
                "distance_from_52w_high_pct": round(
                    (quote["price"] / quote["yearHigh"] - 1) * 100, 2
                )
            },

            "volume": {
                "today": today_vol,
                "avg_30d": avg_vol,
                "zscore": z,
                "flag": vol_flag
            },

            "relative_strength": {
                "stock_30d": round(stock_30d, 2),
                "benchmark": benchmark_name,
                "benchmark_30d": benchmark_30d,
                "relative": round(stock_30d - benchmark_30d, 2)
            },

            "news": fetch_news(symbol, name)
        }

    except Exception as e:
        print(f" Error fetching FMP data for {symbol}: {e}")
        return None

output = {
    "date": str(datetime.now(timezone.utc).date()),
    "stocks": []
}

for s in STOCKS:
    print(f"Processing {s['symbol']} ({s['name']})...")

    if s["source"] == "yfinance":
        stock_data = fetch_yfinance_data(s["symbol"], s["name"], s["country"])
    else:
        stock_data = fetch_fmp_data(s["symbol"], s["name"], s["country"])

    if stock_data:
        output["stocks"].append(stock_data)
        print(f" Successfully processed {s['symbol']}")
    else:
        print(f" Failed to process {s['symbol']}")


print(f"\n Successfully processed {len(output['stocks'])} out of {len(STOCKS)} stocks")
output

# FUNDAMENTAL AI SUMMARY PIPELINE  FINAL!!!


import psycopg2
from psycopg2.extras import execute_batch, RealDictCursor

import psycopg2
import json
from openai import OpenAI
from collections import defaultdict
from datetime import datetime
import numpy as np
from config import AWS_RDS, TICKER_MAPPINGS, OPENAI_API_KEY,FMP_API_KEY


MODEL = "gpt-4o"

# DB_CONFIG = {
#     "host": "equities-first-dev-db.craa4kqs0ndo.ap-south-1.rds.amazonaws.com",
#     "port": 5432,
#     "dbname": "equities_first_dev_db",
#     "user": "ef_dev_user_rw",
#     "password": "ef_dev_user_rw@123!",
#     "sslmode": "require"
# }

DB_CONFIG = {
    "host": AWS_RDS["host"],
    "port": AWS_RDS["port"],
    "dbname": AWS_RDS["database"],
    "user": AWS_RDS["user"],
    "password": AWS_RDS["password"],
    "sslmode": AWS_RDS["sslmode"],
}


client = OpenAI(api_key=OPENAI_API_KEY)


conn = psycopg2.connect(**DB_CONFIG)
cur = conn.cursor()


def convert_numpy_types(obj):
    """Recursively convert numpy types to native Python types for JSON serialization"""
    if isinstance(obj, dict):
        return {key: convert_numpy_types(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [convert_numpy_types(item) for item in obj]
    elif isinstance(obj, np.integer):
        return int(obj)
    elif isinstance(obj, np.floating):
        return float(obj)
    elif isinstance(obj, np.bool_):
        return bool(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    else:
        return obj


def get_stock_id_from_symbol(symbol):
    """Fetch stock_id from database using symbol"""
    cur.execute("""
        SELECT stock_id FROM ingest_db.stocks WHERE ticker = %s
    """, (symbol,))

    result = cur.fetchone()
    if result:
        return result[0]
    else:
        print(f"   Warning: Stock {symbol} not found in database")
        return None


METRICS = {
    "income_statement": [
        "Revenue", "Net Income", "EBITDA", "EPS",
        "Quarterly Revenue (YoY)", "Quarterly Earnings (YoY)"
    ],
    "profitability": [
        "Gross Margin", "Operating Margin", "Profit Margin",
        "Return On Equity", "Return On Assets",
        "Return on capital employed", "Piotroski Score"
    ],
    "cash_flow": [
        "Operating Cash Flow", "Free Cash Flow",
        "FCF Per Share", "SBC Adj. FCF"
    ],
    "balance_sheet": [
        "Cash", "Debt", "Total Assets",
        "Total Liabilities", "Book Value"
    ],
    "capital_structure": [
        "Shares Outstanding", "SBC Impact"
    ]
}


# FETCH FUNDAMENTALS (LATEST ONLY)
def fetch_fundamentals(stock_id):
    fundamentals = defaultdict(dict)

    for section, metric_list in METRICS.items():
        for metric in metric_list:
            cur.execute("""
                SELECT metric_value, period_type, period_label
                FROM ingest_db.stocks_fundamentals
                WHERE stock_id = %s
                  AND metric_type = %s
                ORDER BY captured_date DESC
                LIMIT 1
            """, (stock_id, metric))

            row = cur.fetchone()
            if row:
                fundamentals[section][metric] = {
                    "value": float(row[0]),
                    "period_type": row[1],
                    "period_label": row[2]
                }

    return fundamentals


QUALITY_PROMPT = """
Fundamental screen – Quality
You are an institutional equity analyst supporting Equities First.
Your audience is a portfolio manager and investment committee.
Assess business quality, not short-term price movements.

INPUT DATA (Company Fundamentals):
- income_statement: multi-year revenue, margins, EBITDA, net income
- balance_sheet: cash, debt, assets, liabilities
- cash_flow: operating CF, investing CF, free cash flow
- capital_structure: shares outstanding, SBC, historical dilution
- valuation_metrics: market cap, EV, multiples
- business_context: sector, products, geography

TASK:
Generate a Fundamental Quality AI Summary only.

You must:
1. Provide a one-line Fundamental Quality headline.
2. Provide an AI Confidence score (0–100).
3. List 4–5 quality drivers based on revenue durability, margins, balance sheet, capital allocation, and valuation.
4. Highlight key fundamental strengths (2–3 bullets).
5. Provide exactly 2 upgrade triggers and 2 downgrade triggers tied to financial outcomes.

OUTPUT FORMAT (STRICT):

Fundamental Quality: <headline>
AI Confidence: <0–100>

Quality Drivers:
- <bullet>
- <bullet>
- <bullet>
- <bullet>
- <optional bullet>

Fundamental Strengths:
- <bullet>
- <bullet>
- <optional bullet>

Upgrade Triggers:
- <trigger>
- <trigger>

Downgrade Triggers:
- <trigger>
- <trigger>

CONSTRAINTS:
- Focus on trends, not single-period numbers.
- Reward improving fundamentals more than absolute levels.
- Avoid promotional or speculative language.
- Keep output under 180 words.
"""

RISK_PROMPT = """
Fundament Risk prompt
You are an institutional risk analyst evaluating company fundamentals for Equities First.
Your focus is downside risk, capital impairment, and execution failure.

INPUT DATA (Company Fundamentals):
- income_statement trends
- cash_flow trends and burn rate
- balance_sheet liquidity and leverage
- capital_structure and dilution history
- valuation expectations vs fundamentals
- known operational or regulatory dependencies

TASK:
Generate a Fundamental Risk AI Summary only.

You must:
1. Provide a one-line Fundamental Risk headline.
2. Assign Risk Severity (Low / Medium / High).
3. Provide an AI Confidence score (0–100).
4. List 4–5 concrete fundamental risk drivers tied to cash flow, execution, dilution, margins, and valuation.
5. Describe one realistic downside scenario with estimated equity impact.
6. List 1–2 mitigating factors, if any.

OUTPUT FORMAT (STRICT):

Fundamental Risk: <headline>
Risk Severity: <Low/Medium/High>
AI Confidence: <0–100>

Top Fundamental Risk Drivers:
- <bullet>
- <bullet>
- <bullet>
- <bullet>
- <optional bullet>

Downside Scenario:
Scenario: <1–2 sentences>
Estimated Impact: <equity downside range>
Primary Drivers: <factors>

Risk Mitigants:
- <mitigant>
- <optional mitigant>

CONSTRAINTS:
- Be conservative; assume capital is at risk.
- Do not repeat quality arguments.
- Avoid vague language unless uncertainty is explicit.
- Keep output under 200 words.
"""


SYMBOL_MAPPING = {
    "JD": "9618.HK"  # Map US ticker to HK ticker
}


results = []

print("="*80)
print("PROCESSING STOCKS")
print("="*80)

for stock in output["stocks"]:
    symbol = stock.get("symbol")

    if not symbol:
        print(f"  Skipping stock with no symbol")
        continue

    # Apply symbol mapping if needed
    db_symbol = SYMBOL_MAPPING.get(symbol, symbol)

    print(f"\n→ Processing: {symbol} ({stock.get('name', 'Unknown')})")
    if db_symbol != symbol:
        print(f"  Mapping {symbol} -> {db_symbol} for database lookup")

    # Get stock_id from database using mapped symbol
    stock_id = get_stock_id_from_symbol(db_symbol)

    if stock_id is None:
        print(f"  Stock {db_symbol} not found in database - skipping")
        continue

    print(f"  Found stock_id: {stock_id}")

    # Fetch fundamentals
    fundamentals = fetch_fundamentals(stock_id)

    if not fundamentals or all(not v for v in fundamentals.values()):
        print(f"  No fundamental data found for {symbol}")

    # Convert numpy types to native Python types
    stock_clean = convert_numpy_types(stock)

    model_input = {
        "market_data": stock_clean,
        "fundamentals": fundamentals
    }

    payload = json.dumps(model_input, indent=2)

    print(f"  Calling AI for quality summary...")
    # QUALITY
    quality_resp = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": QUALITY_PROMPT},
            {"role": "user", "content": payload}
        ],
        temperature=0.3,
        max_tokens=900
    )

    print(f"  Calling AI for risk summary...")
    # RISK
    risk_resp = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": RISK_PROMPT},
            {"role": "user", "content": payload}
        ],
        temperature=0.3,
        max_tokens=900
    )

    results.append({
        "symbol": symbol,
        "db_symbol": db_symbol,
        "stock_id": stock_id,
        "company_name": stock.get("name"),
        "quality_summary": quality_resp.choices[0].message.content,
        "risk_summary": risk_resp.choices[0].message.content
    })

    print(f"   Completed {symbol}")


print("\n" + "="*80)
print(f" Generated Fundamental Quality & Risk summaries for {len(results)} stocks")
print("="*80)


print("\n" + "="*80)
print("SAVING TO DATABASE")
print("="*80)

try:
    # Delete existing analysis for these stock_ids
    stock_ids = [r['stock_id'] for r in results]

    if stock_ids:
        print(f"\n→ Deleting existing analysis for stock_ids: {stock_ids}")
        cur.execute("""
            DELETE FROM transform_db.stocks_fundamentals_ai_analysis
            WHERE stock_id = ANY(%s)
        """, (stock_ids,))
        print(f"   Deleted existing records")

        # Insert new analysis
        print(f"\n Inserting {len(results) * 2} new records (Quality + Risk for each stock)...")

        inserted_count = 0
        for result in results:
            # Insert Quality
            cur.execute("""
                INSERT INTO transform_db.stocks_fundamentals_ai_analysis
                (stock_id, analysis_type, analysis_text, generated_by, generated_at)
                VALUES (%s, %s, %s, %s, NOW())
            """, (
                result['stock_id'],
                'Quality',
                result['quality_summary'],
                MODEL
            ))
            inserted_count += 1

            # Insert Risk
            cur.execute("""
                INSERT INTO transform_db.stocks_fundamentals_ai_analysis
                (stock_id, analysis_type, analysis_text, generated_by, generated_at)
                VALUES (%s, %s, %s, %s, NOW())
            """, (
                result['stock_id'],
                'Risk',
                result['risk_summary'],
                MODEL
            ))
            inserted_count += 1

        conn.commit()

        print(f"   Successfully inserted {inserted_count} records")
        print("\n" + "="*80)
        print(" DATABASE SAVE COMPLETE")
        print("="*80)
    else:
        print("  No results to save")

except Exception as e:
    print(f"\n Error saving to database: {e}")
    conn.rollback()

finally:
    cur.close()
    conn.close()

# Display results
print("\n" + "="*80)
print("ANALYSIS RESULTS")
print("="*80)
results